apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cable-ticketing.fullname" . }}-config
  labels:
    {{- include "cable-ticketing.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.backend.env.secretKey | quote }}
  DATABASE_URL: {{ .Values.backend.env.databaseUrl | quote }}
  APP_URL: {{ .Values.backend.env.appUrl | quote }}
  SENDGRID_FROM_EMAIL: {{ .Values.backend.env.sendgridFromEmail | quote }}
